export const products = [
    { id: 1, name: "Холодильник Samsung RT38", price: 14999 },
    { id: 2, name: "Пральна машина LG Inverter", price: 12450 },
    { id: 3, name: "Мікрохвильова піч Gorenje", price: 3250 },
    { id: 4, name: "Пилосос Philips PowerPro", price: 4199 },
    { id: 5, name: "Посудомийна машина Bosch", price: 13700 },
    { id: 6, name: "Електрочайник Tefal", price: 999 },
    { id: 7, name: "Кавоварка DeLonghi", price: 5299 },
    { id: 8, name: "Телевізор Samsung 55\" 4K", price: 17999 },
    { id: 9, name: "Блендер Braun MultiQuick", price: 1899 },
    { id: 10, name: "Тостер Philips Daily Collection", price: 899 },
    { id: 11, name: "Електроплита Gorenje", price: 11200 },
    { id: 12, name: "Фен для волосся Rowenta", price: 780 },
    { id: 13, name: "Міксер Bosch ErgoMixx", price: 1150 },
    { id: 14, name: "Мультиварка Redmond RMC", price: 2990 },
    { id: 15, name: "Обігрівач електричний Saturn", price: 1890 },
    { id: 16, name: "Кондиціонер Cooper&Hunter", price: 21500 },
    { id: 17, name: "Витяжка кухонна Elica", price: 5799 },
    { id: 18, name: "Ваги кухонні Scarlett", price: 459 },
    { id: 19, name: "Праска Philips SteamGlide", price: 1650 },
    { id: 20, name: "Термопот Panasonic", price: 2340 },
    { id: 21, name: "Кулер для води Ecotronic", price: 3999 },
    { id: 22, name: "Машинка для стрижки Braun", price: 1420 },
    { id: 23, name: "Електросушарка для овочів", price: 1250 },
    { id: 24, name: "Очищувач повітря Xiaomi", price: 5699 },
    { id: 25, name: "Мікрохвильова піч Samsung", price: 3850 },
    { id: 26, name: "Телевізор LG OLED 4K", price: 27999 },
    { id: 27, name: "Хлібопічка Moulinex", price: 2999 },
    { id: 28, name: "Електром’ясорубка Zelmer", price: 2450 },
    { id: 29, name: "Індукційна плита Electrolux", price: 7600 },
    { id: 30, name: "Пароочисник Karcher", price: 6890 },
    { id: 31, name: "Кухонний комбайн Bosch", price: 4900 },
    { id: 32, name: "Термометр електронний", price: 299 },
    { id: 33, name: "Фритюрниця Tefal", price: 3550 },
    { id: 34, name: "Конвектор Thermex", price: 2100 },
    { id: 35, name: "Пральна машина Samsung", price: 13499 },
    { id: 36, name: "Електропіч Saturn", price: 2350 },
    { id: 37, name: "Фен-щітка Philips", price: 1350 },
    { id: 38, name: "Масажер для ніг", price: 3690 },
    { id: 39, name: "Машинка для гоління Braun", price: 2750 },
    { id: 40, name: "Кавомолка Scarlett", price: 699 },
    { id: 41, name: "Тепловентилятор Rovus", price: 1250 },
    { id: 42, name: "Пилосос-робот Xiaomi", price: 8999 },
    { id: 43, name: "Посудомийка Whirlpool", price: 11300 },
    { id: 44, name: "Соковижималка Philips", price: 3150 },
    { id: 45, name: "Осушувач повітря Cooper", price: 7400 },
    { id: 46, name: "Телевізор Hisense 50\"", price: 14299 },
    { id: 47, name: "Тостер Tefal Express", price: 950 },
    { id: 48, name: "Сушарка для білизни Gimi", price: 690 },
    { id: 49, name: "Електрокамін Optiflame", price: 11250 },
    { id: 50, name: "Йогуртниця Moulinex", price: 999 },
];
